<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ColorController extends Controller
{
    private $colors = [
        "000000" => [ "name" => "Black"],
        "000080" => [ "name" => "Navy Blue"],
        "0000C8" => [ "name" => "Dark Blue"],
        "0000FF" => [ "name" => "Blue"],
        "000741" => [ "name" => "Stratos"],
        "001B1C" => [ "name" => "Swamp"],
        "002387" => [ "name" => "Resolution Blue"],
        "002900" => [ "name" => "Deep Fir"],
        "002E20" => [ "name" => "Burnham"],
        "002FA7" => [ "name" => "International Klein Blue"],
        "003153" => [ "name" => "Prussian Blue"],
        "003366" => [ "name" => "Midnight Blue"],
        "003399" => [ "name" => "Smalt"],
        "003532" => [ "name" => "Deep Teal"],
        "003E40" => [ "name" => "Cyprus"],
        "004620" => [ "name" => "Kaitoke Green"],
        "0047AB" => [ "name" => "Cobalt"],
        "004816" => [ "name" => "Crusoe"],
        "004950" => [ "name" => "Sherpa Blue"],
        "0056A7" => [ "name" => "Endeavour"],
        "00581A" => [ "name" => "Camarone"],
        "0066CC" => [ "name" => "Science Blue"],
        "0066FF" => [ "name" => "Blue Ribbon"],
        "00755E" => [ "name" => "Tropical Rain Forest"],
        "0076A3" => [ "name" => "Allports"],
        "007BA7" => [ "name" => "Deep Cerulean"],
        "007EC7" => [ "name" => "Lochmara"],
        "007FFF" => [ "name" => "Azure Radiance"],
        "008080" => [ "name" => "Teal"],
        "0095B6" => [ "name" => "Bondi Blue"],
        "009DC4" => [ "name" => "Pacific Blue"],
        "00A693" => [ "name" => "Persian Green"],
        "00A86B" => [ "name" => "Jade"],
        "00CC99" => [ "name" => "Caribbean Green"],
        "00CCCC" => [ "name" => "Robin's Egg Blue"],
        "00FF00" => [ "name" => "Green"],
        "00FF7F" => [ "name" => "Spring Green"],
        "00FFFF" => [ "name" => "Cyan / Aqua"],
        "010D1A" => [ "name" => "Blue Charcoal"],
        "011635" => [ "name" => "Midnight"],
        "011D13" => [ "name" => "Holly"],
        "012731" => [ "name" => "Daintree"],
        "01361C" => [ "name" => "Cardin Green"],
        "01371A" => [ "name" => "County Green"],
        "013E62" => [ "name" => "Astronaut Blue"],
        "013F6A" => [ "name" => "Regal Blue"],
        "014B43" => [ "name" => "Aqua Deep"],
        "015E85" => [ "name" => "Orient"],
        "016162" => [ "name" => "Blue Stone"],
        "016D39" => [ "name" => "Fun Green"],
        "01796F" => [ "name" => "Pine Green"],
        "017987" => [ "name" => "Blue Lagoon"],
        "01826B" => [ "name" => "Deep Sea"],
        "01A368" => [ "name" => "Green Haze"],
        "022D15" => [ "name" => "English Holly"],
        "02402C" => [ "name" => "Sherwood Green"],
        "02478E" => [ "name" => "Congress Blue"],
        "024E46" => [ "name" => "Evening Sea"],
        "026395" => [ "name" => "Bahama Blue"],
        "02866F" => [ "name" => "Observatory"],
        "02A4D3" => [ "name" => "Cerulean"],
        "03163C" => [ "name" => "Tangaroa"],
        "032B52" => [ "name" => "Green Vogue"],
        "036A6E" => [ "name" => "Mosque"],
        "041004" => [ "name" => "Midnight Moss"],
        "041322" => [ "name" => "Black Pearl"],
        "042E4C" => [ "name" => "Blue Whale"],
        "044022" => [ "name" => "Zuccini"],
        "044259" => [ "name" => "Teal Blue"],
        "051040" => [ "name" => "Deep Cove"],
        "051657" => [ "name" => "Gulf Blue"],
        "055989" => [ "name" => "Venice Blue"],
        "056F57" => [ "name" => "Watercourse"],
        "062A78" => [ "name" => "Catalina Blue"],
        "063537" => [ "name" => "Tiber"],
        "069B81" => [ "name" => "Gossamer"],
        "06A189" => [ "name" => "Niagara"],
        "073A50" => [ "name" => "Tarawera"],
        "080110" => [ "name" => "Jaguar"],
        "081910" => [ "name" => "Black Bean"],
        "082567" => [ "name" => "Deep Sapphire"],
        "088370" => [ "name" => "Elf Green"],
        "08E8DE" => [ "name" => "Bright Turquoise"],
        "092256" => [ "name" => "Downriver"],
        "09230F" => [ "name" => "Palm Green"],
        "09255D" => [ "name" => "Madison"],
        "093624" => [ "name" => "Bottle Green"],
        "095859" => [ "name" => "Deep Sea Green"],
        "097F4B" => [ "name" => "Salem"],
        "0A001C" => [ "name" => "Black Russian"],
        "0A480D" => [ "name" => "Dark Fern"],
        "0A6906" => [ "name" => "Japanese Laurel"],
        "0A6F75" => [ "name" => "Atoll"],
        "0B0B0B" => [ "name" => "Cod Gray"],
        "0B0F08" => [ "name" => "Marshland"],
        "0B1107" => [ "name" => "Gordons Green"],
        "0B1304" => [ "name" => "Black Forest"],
        "0B6207" => [ "name" => "San Felix"],
        "0BDA51" => [ "name" => "Malachite"],
        "0C0B1D" => [ "name" => "Ebony"],
        "0C0D0F" => [ "name" => "Woodsmoke"],
        "0C1911" => [ "name" => "Racing Green"],
        "0C7A79" => [ "name" => "Surfie Green"],
        "0C8990" => [ "name" => "Blue Chill"],
        "0D0332" => [ "name" => "Black Rock"],
        "0D1117" => [ "name" => "Bunker"],
        "0D1C19" => [ "name" => "Aztec"],
        "0D2E1C" => [ "name" => "Bush"],
        "0E0E18" => [ "name" => "Cinder"],
        "0E2A30" => [ "name" => "Firefly"],
        "0F2D9E" => [ "name" => "Torea Bay"],
        "10121D" => [ "name" => "Vulcan"],
        "101405" => [ "name" => "Green Waterloo"],
        "105852" => [ "name" => "Eden"],
        "110C6C" => [ "name" => "Arapawa"],
        "120A8F" => [ "name" => "Ultramarine"],
        "123447" => [ "name" => "Elephant"],
        "126B40" => [ "name" => "Jewel"],
        "130000" => [ "name" => "Diesel"],
        "130A06" => [ "name" => "Asphalt"],
        "13264D" => [ "name" => "Blue Zodiac"],
        "134F19" => [ "name" => "Parsley"],
        "140600" => [ "name" => "Nero"],
        "1450AA" => [ "name" => "Tory Blue"],
        "151F4C" => [ "name" => "Bunting"],
        "1560BD" => [ "name" => "Denim"],
        "15736B" => [ "name" => "Genoa"],
        "161928" => [ "name" => "Mirage"],
        "161D10" => [ "name" => "Hunter Green"],
        "162A40" => [ "name" => "Big Stone"],
        "163222" => [ "name" => "Celtic"],
        "16322C" => [ "name" => "Timber Green"],
        "163531" => [ "name" => "Gable Green"],
        "171F04" => [ "name" => "Pine Tree"],
        "175579" => [ "name" => "Chathams Blue"],
        "182D09" => [ "name" => "Deep Forest Green"],
        "18587A" => [ "name" => "Blumine"],
        "19330E" => [ "name" => "Palm Leaf"],
        "193751" => [ "name" => "Nile Blue"],
        "1959A8" => [ "name" => "Fun Blue"],
        "1A1A68" => [ "name" => "Lucky Point"],
        "1AB385" => [ "name" => "Mountain Meadow"],
        "1B0245" => [ "name" => "Tolopea"],
        "1B1035" => [ "name" => "Haiti"],
        "1B127B" => [ "name" => "Deep Koamaru"],
        "1B1404" => [ "name" => "Acadia"],
        "1B2F11" => [ "name" => "Seaweed"],
        "1B3162" => [ "name" => "Biscay"],
        "1B659D" => [ "name" => "Matisse"],
        "1C1208" => [ "name" => "Crowshead"],
        "1C1E13" => [ "name" => "Rangoon Green"],
        "1C39BB" => [ "name" => "Persian Blue"],
        "1C402E" => [ "name" => "Everglade"],
        "1C7C7D" => [ "name" => "Elm"],
        "1D6142" => [ "name" => "Green Pea"],
        "1E0F04" => [ "name" => "Creole"],
        "1E1609" => [ "name" => "Karaka"],
        "1E1708" => [ "name" => "El Paso"],
        "1E385B" => [ "name" => "Cello"],
        "1E433C" => [ "name" => "Te Papa Green"],
        "1E90FF" => [ "name" => "Dodger Blue"],
        "1E9AB0" => [ "name" => "Eastern Blue"],
        "1F120F" => [ "name" => "Night Rider"],
        "1FC2C2" => [ "name" => "Java"],
        "20208D" => [ "name" => "Jacksons Purple"],
        "202E54" => [ "name" => "Cloud Burst"],
        "204852" => [ "name" => "Blue Dianne"],
        "211A0E" => [ "name" => "Eternity"],
        "220878" => [ "name" => "Deep Blue"],
        "228B22" => [ "name" => "Forest Green"],
        "233418" => [ "name" => "Mallard"],
        "240A40" => [ "name" => "Violet"],
        "240C02" => [ "name" => "Kilamanjaro"],
        "242A1D" => [ "name" => "Log Cabin"],
        "242E16" => [ "name" => "Black Olive"],
        "24500F" => [ "name" => "Green House"],
        "251607" => [ "name" => "Graphite"],
        "251706" => [ "name" => "Cannon Black"],
        "251F4F" => [ "name" => "Port Gore"],
        "25272C" => [ "name" => "Shark"],
        "25311C" => [ "name" => "Green Kelp"],
        "2596D1" => [ "name" => "Curious Blue"],
        "260368" => [ "name" => "Paua"],
        "26056A" => [ "name" => "Paris M"],
        "261105" => [ "name" => "Wood Bark"],
        "261414" => [ "name" => "Gondola"],
        "262335" => [ "name" => "Steel Gray"],
        "26283B" => [ "name" => "Ebony Clay"],
        "273A81" => [ "name" => "Bay of Many"],
        "27504B" => [ "name" => "Plantation"],
        "278A5B" => [ "name" => "Eucalyptus"],
        "281E15" => [ "name" => "Oil"],
        "283A77" => [ "name" => "Astronaut"],
        "286ACD" => [ "name" => "Mariner"],
        "290C5E" => [ "name" => "Violent Violet"],
        "292130" => [ "name" => "Bastille"],
        "292319" => [ "name" => "Zeus"],
        "292937" => [ "name" => "Charade"],
        "297B9A" => [ "name" => "Jelly Bean"],
        "29AB87" => [ "name" => "Jungle Green"],
        "2A0359" => [ "name" => "Cherry Pie"],
        "2A140E" => [ "name" => "Coffee Bean"],
        "2A2630" => [ "name" => "Baltic Sea"],
        "2A380B" => [ "name" => "Turtle Green"],
        "2A52BE" => [ "name" => "Cerulean Blue"],
        "2B0202" => [ "name" => "Sepia Black"],
        "2B194F" => [ "name" => "Valhalla"],
        "2B3228" => [ "name" => "Heavy Metal"],
        "2C0E8C" => [ "name" => "Blue Gem"],
        "2C1632" => [ "name" => "Revolver"],
        "2C2133" => [ "name" => "Bleached Cedar"],
        "2C8C84" => [ "name" => "Lochinvar"],
        "2D2510" => [ "name" => "Mikado"],
        "2D383A" => [ "name" => "Outer Space"],
        "2D569B" => [ "name" => "St Tropaz"],
        "2E0329" => [ "name" => "Jacaranda"],
        "2E1905" => [ "name" => "Jacko Bean"],
        "2E3222" => [ "name" => "Rangitoto"],
        "2E3F62" => [ "name" => "Rhino"],
        "2E8B57" => [ "name" => "Sea Green"],
        "2EBFD4" => [ "name" => "Scooter"],
        "2F270E" => [ "name" => "Onion"],
        "2F3CB3" => [ "name" => "Governor Bay"],
        "2F519E" => [ "name" => "Sapphire"],
        "2F5A57" => [ "name" => "Spectra"],
        "2F6168" => [ "name" => "Casal"],
        "300529" => [ "name" => "Melanzane"],
        "301F1E" => [ "name" => "Cocoa Brown"],
        "302A0F" => [ "name" => "Woodrush"],
        "304B6A" => [ "name" => "San Juan"],
        "30D5C8" => [ "name" => "Turquoise"],
        "311C17" => [ "name" => "Eclipse"],
        "314459" => [ "name" => "Pickled Bluewood"],
        "315BA1" => [ "name" => "Azure"],
        "31728D" => [ "name" => "Calypso"],
        "317D82" => [ "name" => "Paradiso"],
        "32127A" => [ "name" => "Persian Indigo"],
        "32293A" => [ "name" => "Blackcurrant"],
        "323232" => [ "name" => "Mine Shaft"],
        "325D52" => [ "name" => "Stromboli"],
        "327C14" => [ "name" => "Bilbao"],
        "327DA0" => [ "name" => "Astral"],
        "33036B" => [ "name" => "Christalle"],
        "33292F" => [ "name" => "Thunder"],
        "33CC99" => [ "name" => "Shamrock"],
        "341515" => [ "name" => "Tamarind"],
        "350036" => [ "name" => "Mardi Gras"],
        "350E42" => [ "name" => "Valentino"],
        "350E57" => [ "name" => "Jagger"],
        "353542" => [ "name" => "Tuna"],
        "354E8C" => [ "name" => "Chambray"],
        "363050" => [ "name" => "Martinique"],
        "363534" => [ "name" => "Tuatara"],
        "363C0D" => [ "name" => "Waiouru"],
        "36747D" => [ "name" => "Ming"],
        "368716" => [ "name" => "La Palma"],
        "370202" => [ "name" => "Chocolate"],
        "371D09" => [ "name" => "Clinker"],
        "37290E" => [ "name" => "Brown Tumbleweed"],
        "373021" => [ "name" => "Birch"],
        "377475" => [ "name" => "Oracle"],
        "380474" => [ "name" => "Blue Diamond"],
        "381A51" => [ "name" => "Grape"],
        "383533" => [ "name" => "Dune"],
        "384555" => [ "name" => "Oxford Blue"],
        "384910" => [ "name" => "Clover"],
        "394851" => [ "name" => "Limed Spruce"],
        "396413" => [ "name" => "Dell"],
        "3A0020" => [ "name" => "Toledo"],
        "3A2010" => [ "name" => "Sambuca"],
        "3A2A6A" => [ "name" => "Jacarta"],
        "3A686C" => [ "name" => "William"],
        "3A6A47" => [ "name" => "Killarney"],
        "3AB09E" => [ "name" => "Keppel"],
        "3B000B" => [ "name" => "Temptress"],
        "3B0910" => [ "name" => "Aubergine"],
        "3B1F1F" => [ "name" => "Jon"],
        "3B2820" => [ "name" => "Treehouse"],
        "3B7A57" => [ "name" => "Amazon"],
        "3B91B4" => [ "name" => "Boston Blue"],
        "3C0878" => [ "name" => "Windsor"],
        "3C1206" => [ "name" => "Rebel"],
        "3C1F76" => [ "name" => "Meteorite"],
        "3C2005" => [ "name" => "Dark Ebony"],
        "3C3910" => [ "name" => "Camouflage"],
        "3C4151" => [ "name" => "Bright Gray"],
        "3C4443" => [ "name" => "Cape Cod"],
        "3C493A" => [ "name" => "Lunar Green"],
        "3D0C02" => [ "name" => "Bean  "],
        "3D2B1F" => [ "name" => "Bistre"],
        "3D7D52" => [ "name" => "Goblin"],
        "3E0480" => [ "name" => "Kingfisher Daisy"],
        "3E1C14" => [ "name" => "Cedar"],
        "3E2B23" => [ "name" => "English Walnut"],
        "3E2C1C" => [ "name" => "Black Marlin"],
        "3E3A44" => [ "name" => "Ship Gray"],
        "3EABBF" => [ "name" => "Pelorous"],
        "3F2109" => [ "name" => "Bronze"],
        "3F2500" => [ "name" => "Cola"],
        "3F3002" => [ "name" => "Madras"],
        "3F307F" => [ "name" => "Minsk"],
        "3F4C3A" => [ "name" => "Cabbage Pont"],
        "3F583B" => [ "name" => "Tom Thumb"],
        "3F5D53" => [ "name" => "Mineral Green"],
        "3FC1AA" => [ "name" => "Puerto Rico"],
        "3FFF00" => [ "name" => "Harlequin"],
        "401801" => [ "name" => "Brown Pod"],
        "40291D" => [ "name" => "Cork"],
        "403B38" => [ "name" => "Masala"],
        "403D19" => [ "name" => "Thatch Green"],
        "405169" => [ "name" => "Fiord"],
        "40826D" => [ "name" => "Viridian"],
        "40A860" => [ "name" => "Chateau Green"],
        "410056" => [ "name" => "Ripe Plum"],
        "411F10" => [ "name" => "Paco"],
        "412010" => [ "name" => "Deep Oak"],
        "413C37" => [ "name" => "Merlin"],
        "414257" => [ "name" => "Gun Powder"],
        "414C7D" => [ "name" => "East Bay"],
        "4169E1" => [ "name" => "Royal Blue"],
        "41AA78" => [ "name" => "Ocean Green"],
        "420303" => [ "name" => "Burnt Maroon"],
        "423921" => [ "name" => "Lisbon Brown"],
        "427977" => [ "name" => "Faded Jade"],
        "431560" => [ "name" => "Scarlet Gum"],
        "433120" => [ "name" => "Iroko"],
        "433E37" => [ "name" => "Armadillo"],
        "434C59" => [ "name" => "River Bed"],
        "436A0D" => [ "name" => "Green Leaf"],
        "44012D" => [ "name" => "Barossa"],
        "441D00" => [ "name" => "Morocco Brown"],
        "444954" => [ "name" => "Mako"],
        "454936" => [ "name" => "Kelp"],
        "456CAC" => [ "name" => "San Marino"],
        "45B1E8" => [ "name" => "Picton Blue"],
        "460B41" => [ "name" => "Loulou"],
        "462425" => [ "name" => "Crater Brown"],
        "465945" => [ "name" => "Gray Asparagus"],
        "4682B4" => [ "name" => "Steel Blue"],
        "480404" => [ "name" => "Rustic Red"],
        "480607" => [ "name" => "Bulgarian Rose"],
        "480656" => [ "name" => "Clairvoyant"],
        "481C1C" => [ "name" => "Cocoa Bean"],
        "483131" => [ "name" => "Woody Brown"],
        "483C32" => [ "name" => "Taupe"],
        "49170C" => [ "name" => "Van Cleef"],
        "492615" => [ "name" => "Brown Derby"],
        "49371B" => [ "name" => "Metallic Bronze"],
        "495400" => [ "name" => "Verdun Green"],
        "496679" => [ "name" => "Blue Bayoux"],
        "497183" => [ "name" => "Bismark"],
        "4A2A04" => [ "name" => "Bracken"],
        "4A3004" => [ "name" => "Deep Bronze"],
        "4A3C30" => [ "name" => "Mondo"],
        "4A4244" => [ "name" => "Tundora"],
        "4A444B" => [ "name" => "Gravel"],
        "4A4E5A" => [ "name" => "Trout"],
        "4B0082" => [ "name" => "Pigment Indigo"],
        "4B5D52" => [ "name" => "Nandor"],
        "4C3024" => [ "name" => "Saddle"],
        "4C4F56" => [ "name" => "Abbey"],
        "4D0135" => [ "name" => "Blackberry"],
        "4D0A18" => [ "name" => "Cab Sav"],
        "4D1E01" => [ "name" => "Indian Tan"],
        "4D282D" => [ "name" => "Cowboy"],
        "4D282E" => [ "name" => "Livid Brown"],
        "4D3833" => [ "name" => "Rock"],
        "4D3D14" => [ "name" => "Punga"],
        "4D400F" => [ "name" => "Bronzetone"],
        "4D5328" => [ "name" => "Woodland"],
        "4E0606" => [ "name" => "Mahogany"],
        "4E2A5A" => [ "name" => "Bossanova"],
        "4E3B41" => [ "name" => "Matterhorn"],
        "4E420C" => [ "name" => "Bronze Olive"],
        "4E4562" => [ "name" => "Mulled Wine"],
        "4E6649" => [ "name" => "Axolotl"],
        "4E7F9E" => [ "name" => "Wedgewood"],
        "4EABD1" => [ "name" => "Shakespeare"],
        "4F1C70" => [ "name" => "Honey Flower"],
        "4F2398" => [ "name" => "Daisy Bush"],
        "4F69C6" => [ "name" => "Indigo"],
        "4F7942" => [ "name" => "Fern Green"],
        "4F9D5D" => [ "name" => "Fruit Salad"],
        "4FA83D" => [ "name" => "Apple"],
        "504351" => [ "name" => "Mortar"],
        "507096" => [ "name" => "Kashmir Blue"],
        "507672" => [ "name" => "Cutty Sark"],
        "50C878" => [ "name" => "Emerald"],
        "514649" => [ "name" => "Emperor"],
        "516E3D" => [ "name" => "Chalet Green"],
        "517C66" => [ "name" => "Como"],
        "51808F" => [ "name" => "Smalt Blue"],
        "52001F" => [ "name" => "Castro"],
        "520C17" => [ "name" => "Maroon Oak"],
        "523C94" => [ "name" => "Gigas"],
        "533455" => [ "name" => "Voodoo"],
        "534491" => [ "name" => "Victoria"],
        "53824B" => [ "name" => "Hippie Green"],
        "541012" => [ "name" => "Heath"],
        "544333" => [ "name" => "Judge Gray"],
        "54534D" => [ "name" => "Fuscous Gray"],
        "549019" => [ "name" => "Vida Loca"],
        "55280C" => [ "name" => "Cioccolato"],
        "555B10" => [ "name" => "Saratoga"],
        "556D56" => [ "name" => "Finlandia"],
        "5590D9" => [ "name" => "Havelock Blue"],
        "56B4BE" => [ "name" => "Fountain Blue"],
        "578363" => [ "name" => "Spring Leaves"],
        "583401" => [ "name" => "Saddle Brown"],
        "585562" => [ "name" => "Scarpa Flow"],
        "587156" => [ "name" => "Cactus"],
        "589AAF" => [ "name" => "Hippie Blue"],
        "591D35" => [ "name" => "Wine Berry"],
        "592804" => [ "name" => "Brown Bramble"],
        "593737" => [ "name" => "Congo Brown"],
        "594433" => [ "name" => "Millbrook"],
        "5A6E9C" => [ "name" => "Waikawa Gray"],
        "5A87A0" => [ "name" => "Horizon"],
        "5B3013" => [ "name" => "Jambalaya"],
        "5C0120" => [ "name" => "Bordeaux"],
        "5C0536" => [ "name" => "Mulberry Wood"],
        "5C2E01" => [ "name" => "Carnaby Tan"],
        "5C5D75" => [ "name" => "Comet"],
        "5D1E0F" => [ "name" => "Redwood"],
        "5D4C51" => [ "name" => "Don Juan"],
        "5D5C58" => [ "name" => "Chicago"],
        "5D5E37" => [ "name" => "Verdigris"],
        "5D7747" => [ "name" => "Dingley"],
        "5DA19F" => [ "name" => "Breaker Bay"],
        "5E483E" => [ "name" => "Kabul"],
        "5E5D3B" => [ "name" => "Hemlock"],
        "5F3D26" => [ "name" => "Irish Coffee"],
        "5F5F6E" => [ "name" => "Mid Gray"],
        "5F6672" => [ "name" => "Shuttle Gray"],
        "5FA777" => [ "name" => "Aqua Forest"],
        "5FB3AC" => [ "name" => "Tradewind"],
        "604913" => [ "name" => "Horses Neck"],
        "605B73" => [ "name" => "Smoky"],
        "606E68" => [ "name" => "Corduroy"],
        "6093D1" => [ "name" => "Danube"],
        "612718" => [ "name" => "Espresso"],
        "614051" => [ "name" => "Eggplant"],
        "615D30" => [ "name" => "Costa Del Sol"],
        "61845F" => [ "name" => "Glade Green"],
        "622F30" => [ "name" => "Buccaneer"],
        "623F2D" => [ "name" => "Quincy"],
        "624E9A" => [ "name" => "Butterfly Bush"],
        "625119" => [ "name" => "West Coast"],
        "626649" => [ "name" => "Finch"],
        "639A8F" => [ "name" => "Patina"],
        "63B76C" => [ "name" => "Fern"],
        "6456B7" => [ "name" => "Blue Violet"],
        "646077" => [ "name" => "Dolphin"],
        "646463" => [ "name" => "Storm Dust"],
        "646A54" => [ "name" => "Siam"],
        "646E75" => [ "name" => "Nevada"],
        "6495ED" => [ "name" => "Cornflower Blue"],
        "64CCDB" => [ "name" => "Viking"],
        "65000B" => [ "name" => "Rosewood"],
        "651A14" => [ "name" => "Cherrywood"],
        "652DC1" => [ "name" => "Purple Heart"],
        "657220" => [ "name" => "Fern Frond"],
        "65745D" => [ "name" => "Willow Grove"],
        "65869F" => [ "name" => "Hoki"],
        "660045" => [ "name" => "Pompadour"],
        "660099" => [ "name" => "Purple"],
        "66023C" => [ "name" => "Tyrian Purple"],
        "661010" => [ "name" => "Dark Tan"],
        "66B58F" => [ "name" => "Silver Tree"],
        "66FF00" => [ "name" => "Bright Green"],
        "66FF66" => [ "name" => "Screamin' Green"],
        "67032D" => [ "name" => "Black Rose"],
        "675FA6" => [ "name" => "Scampi"],
        "676662" => [ "name" => "Ironside Gray"],
        "678975" => [ "name" => "Viridian Green"],
        "67A712" => [ "name" => "Christi"],
        "683600" => [ "name" => "Nutmeg Wood Finish"],
        "685558" => [ "name" => "Zambezi"],
        "685E6E" => [ "name" => "Salt Box"],
        "692545" => [ "name" => "Tawny Port"],
        "692D54" => [ "name" => "Finn"],
        "695F62" => [ "name" => "Scorpion"],
        "697E9A" => [ "name" => "Lynch"],
        "6A442E" => [ "name" => "Spice"],
        "6A5D1B" => [ "name" => "Himalaya"],
        "6A6051" => [ "name" => "Soya Bean"],
        "6B2A14" => [ "name" => "Hairy Heath"],
        "6B3FA0" => [ "name" => "Royal Purple"],
        "6B4E31" => [ "name" => "Shingle Fawn"],
        "6B5755" => [ "name" => "Dorado"],
        "6B8BA2" => [ "name" => "Bermuda Gray"],
        "6B8E23" => [ "name" => "Olive Drab"],
        "6C3082" => [ "name" => "Eminence"],
        "6CDAE7" => [ "name" => "Turquoise Blue"],
        "6D0101" => [ "name" => "Lonestar"],
        "6D5E54" => [ "name" => "Pine Cone"],
        "6D6C6C" => [ "name" => "Dove Gray"],
        "6D9292" => [ "name" => "Juniper"],
        "6D92A1" => [ "name" => "Gothic"],
        "6E0902" => [ "name" => "Red Oxide"],
        "6E1D14" => [ "name" => "Moccaccino"],
        "6E4826" => [ "name" => "Pickled Bean"],
        "6E4B26" => [ "name" => "Dallas"],
        "6E6D57" => [ "name" => "Kokoda"],
        "6E7783" => [ "name" => "Pale Sky"],
        "6F440C" => [ "name" => "Cafe Royale"],
        "6F6A61" => [ "name" => "Flint"],
        "6F8E63" => [ "name" => "Highland"],
        "6F9D02" => [ "name" => "Limeade"],
        "6FD0C5" => [ "name" => "Downy"],
        "701C1C" => [ "name" => "Persian Plum"],
        "704214" => [ "name" => "Sepia"],
        "704A07" => [ "name" => "Antique Bronze"],
        "704F50" => [ "name" => "Ferra"],
        "706555" => [ "name" => "Coffee"],
        "708090" => [ "name" => "Slate Gray"],
        "711A00" => [ "name" => "Cedar Wood Finish"],
        "71291D" => [ "name" => "Metallic Copper"],
        "714693" => [ "name" => "Affair"],
        "714AB2" => [ "name" => "Studio"],
        "715D47" => [ "name" => "Tobacco Brown"],
        "716338" => [ "name" => "Yellow Metal"],
        "716B56" => [ "name" => "Peat"],
        "716E10" => [ "name" => "Olivetone"],
        "717486" => [ "name" => "Storm Gray"],
        "718080" => [ "name" => "Sirocco"],
        "71D9E2" => [ "name" => "Aquamarine Blue"],
        "72010F" => [ "name" => "Venetian Red"],
        "724A2F" => [ "name" => "Old Copper"],
        "726D4E" => [ "name" => "Go Ben"],
        "727B89" => [ "name" => "Raven"],
        "731E8F" => [ "name" => "Seance"],
        "734A12" => [ "name" => "Raw Umber"],
        "736C9F" => [ "name" => "Kimberly"],
        "736D58" => [ "name" => "Crocodile"],
        "737829" => [ "name" => "Crete"],
        "738678" => [ "name" => "Xanadu"],
        "74640D" => [ "name" => "Spicy Mustard"],
        "747D63" => [ "name" => "Limed Ash"],
        "747D83" => [ "name" => "Rolling Stone"],
        "748881" => [ "name" => "Blue Smoke"],
        "749378" => [ "name" => "Laurel"],
        "74C365" => [ "name" => "Mantis"],
        "755A57" => [ "name" => "Russett"],
        "7563A8" => [ "name" => "Deluge"],
        "76395D" => [ "name" => "Cosmic"],
        "7666C6" => [ "name" => "Blue Marguerite"],
        "76BD17" => [ "name" => "Lima"],
        "76D7EA" => [ "name" => "Sky Blue"],
        "770F05" => [ "name" => "Dark Burgundy"],
        "771F1F" => [ "name" => "Crown of Thorns"],
        "773F1A" => [ "name" => "Walnut"],
        "776F61" => [ "name" => "Pablo"],
        "778120" => [ "name" => "Pacifika"],
        "779E86" => [ "name" => "Oxley"],
        "77DD77" => [ "name" => "Pastel Green"],
        "780109" => [ "name" => "Japanese Maple"],
        "782D19" => [ "name" => "Mocha"],
        "782F16" => [ "name" => "Peanut"],
        "78866B" => [ "name" => "Camouflage Green"],
        "788A25" => [ "name" => "Wasabi"],
        "788BBA" => [ "name" => "Ship Cove"],
        "78A39C" => [ "name" => "Sea Nymph"],
        "795D4C" => [ "name" => "Roman Coffee"],
        "796878" => [ "name" => "Old Lavender"],
        "796989" => [ "name" => "Rum"],
        "796A78" => [ "name" => "Fedora"],
        "796D62" => [ "name" => "Sandstone"],
        "79DEEC" => [ "name" => "Spray"],
        "7A013A" => [ "name" => "Siren"],
        "7A58C1" => [ "name" => "Fuchsia Blue"],
        "7A7A7A" => [ "name" => "Boulder"],
        "7A89B8" => [ "name" => "Wild Blue Yonder"],
        "7AC488" => [ "name" => "De York"],
        "7B3801" => [ "name" => "Red Beech"],
        "7B3F00" => [ "name" => "Cinnamon"],
        "7B6608" => [ "name" => "Yukon Gold"],
        "7B7874" => [ "name" => "Tapa"],
        "7B7C94" => [ "name" => "Waterloo "],
        "7B8265" => [ "name" => "Flax Smoke"],
        "7B9F80" => [ "name" => "Amulet"],
        "7BA05B" => [ "name" => "Asparagus"],
        "7C1C05" => [ "name" => "Kenyan Copper"],
        "7C7631" => [ "name" => "Pesto"],
        "7C778A" => [ "name" => "Topaz"],
        "7C7B7A" => [ "name" => "Concord"],
        "7C7B82" => [ "name" => "Jumbo"],
        "7C881A" => [ "name" => "Trendy Green"],
        "7CA1A6" => [ "name" => "Gumbo"],
        "7CB0A1" => [ "name" => "Acapulco"],
        "7CB7BB" => [ "name" => "Neptune"],
        "7D2C14" => [ "name" => "Pueblo"],
        "7DA98D" => [ "name" => "Bay Leaf"],
        "7DC8F7" => [ "name" => "Malibu"],
        "7DD8C6" => [ "name" => "Bermuda"],
        "7E3A15" => [ "name" => "Copper Canyon"],
        "7F1734" => [ "name" => "Claret"],
        "7F3A02" => [ "name" => "Peru Tan"],
        "7F626D" => [ "name" => "Falcon"],
        "7F7589" => [ "name" => "Mobster"],
        "7F76D3" => [ "name" => "Moody Blue"],
        "7FFF00" => [ "name" => "Chartreuse"],
        "7FFFD4" => [ "name" => "Aquamarine"],
        "800000" => [ "name" => "Maroon"],
        "800B47" => [ "name" => "Rose Bud Cherry"],
        "801818" => [ "name" => "Falu Red"],
        "80341F" => [ "name" => "Red Robin"],
        "803790" => [ "name" => "Vivid Violet"],
        "80461B" => [ "name" => "Russet"],
        "807E79" => [ "name" => "Friar Gray"],
        "808000" => [ "name" => "Olive"],
        "808080" => [ "name" => "Gray"],
        "80B3AE" => [ "name" => "Gulf Stream"],
        "80B3C4" => [ "name" => "Glacier"],
        "80CCEA" => [ "name" => "Seagull"],
        "81422C" => [ "name" => "Nutmeg"],
        "816E71" => [ "name" => "Spicy Pink"],
        "817377" => [ "name" => "Empress"],
        "819885" => [ "name" => "Spanish Green"],
        "826F65" => [ "name" => "Sand Dune"],
        "828685" => [ "name" => "Gunsmoke"],
        "828F72" => [ "name" => "Battleship Gray"],
        "831923" => [ "name" => "Merlot"],
        "837050" => [ "name" => "Shadow"],
        "83AA5D" => [ "name" => "Chelsea Cucumber"],
        "83D0C6" => [ "name" => "Monte Carlo"],
        "843179" => [ "name" => "Plum"],
        "84A0A0" => [ "name" => "Granny Smith"],
        "8581D9" => [ "name" => "Chetwode Blue"],
        "858470" => [ "name" => "Bandicoot"],
        "859FAF" => [ "name" => "Bali Hai"],
        "85C4CC" => [ "name" => "Half Baked"],
        "860111" => [ "name" => "Red Devil"],
        "863C3C" => [ "name" => "Lotus"],
        "86483C" => [ "name" => "Ironstone"],
        "864D1E" => [ "name" => "Bull Shot"],
        "86560A" => [ "name" => "Rusty Nail"],
        "868974" => [ "name" => "Bitter"],
        "86949F" => [ "name" => "Regent Gray"],
        "871550" => [ "name" => "Disco"],
        "87756E" => [ "name" => "Americano"],
        "877C7B" => [ "name" => "Hurricane"],
        "878D91" => [ "name" => "Oslo Gray"],
        "87AB39" => [ "name" => "Sushi"],
        "885342" => [ "name" => "Spicy Mix"],
        "886221" => [ "name" => "Kumera"],
        "888387" => [ "name" => "Suva Gray"],
        "888D65" => [ "name" => "Avocado"],
        "893456" => [ "name" => "Camelot"],
        "893843" => [ "name" => "Solid Pink"],
        "894367" => [ "name" => "Cannon Pink"],
        "897D6D" => [ "name" => "Makara"],
        "8A3324" => [ "name" => "Burnt Umber"],
        "8A73D6" => [ "name" => "True V"],
        "8A8360" => [ "name" => "Clay Creek"],
        "8A8389" => [ "name" => "Monsoon"],
        "8A8F8A" => [ "name" => "Stack"],
        "8AB9F1" => [ "name" => "Jordy Blue"],
        "8B00FF" => [ "name" => "Electric Violet"],
        "8B0723" => [ "name" => "Monarch"],
        "8B6B0B" => [ "name" => "Corn Harvest"],
        "8B8470" => [ "name" => "Olive Haze"],
        "8B847E" => [ "name" => "Schooner"],
        "8B8680" => [ "name" => "Natural Gray"],
        "8B9C90" => [ "name" => "Mantle"],
        "8B9FEE" => [ "name" => "Portage"],
        "8BA690" => [ "name" => "Envy"],
        "8BA9A5" => [ "name" => "Cascade"],
        "8BE6D8" => [ "name" => "Riptide"],
        "8C055E" => [ "name" => "Cardinal Pink"],
        "8C472F" => [ "name" => "Mule Fawn"],
        "8C5738" => [ "name" => "Potters Clay"],
        "8C6495" => [ "name" => "Trendy Pink"],
        "8D0226" => [ "name" => "Paprika"],
        "8D3D38" => [ "name" => "Sanguine Brown"],
        "8D3F3F" => [ "name" => "Tosca"],
        "8D7662" => [ "name" => "Cement"],
        "8D8974" => [ "name" => "Granite Green"],
        "8D90A1" => [ "name" => "Manatee"],
        "8DA8CC" => [ "name" => "Polo Blue"],
        "8E0000" => [ "name" => "Red Berry"],
        "8E4D1E" => [ "name" => "Rope"],
        "8E6F70" => [ "name" => "Opium"],
        "8E775E" => [ "name" => "Domino"],
        "8E8190" => [ "name" => "Mamba"],
        "8EABC1" => [ "name" => "Nepal"],
        "8F021C" => [ "name" => "Pohutukawa"],
        "8F3E33" => [ "name" => "El Salva"],
        "8F4B0E" => [ "name" => "Korma"],
        "8F8176" => [ "name" => "Squirrel"],
        "8FD6B4" => [ "name" => "Vista Blue"],
        "900020" => [ "name" => "Burgundy"],
        "901E1E" => [ "name" => "Old Brick"],
        "907874" => [ "name" => "Hemp"],
        "907B71" => [ "name" => "Almond Frost"],
        "908D39" => [ "name" => "Sycamore"],
        "92000A" => [ "name" => "Sangria"],
        "924321" => [ "name" => "Cumin"],
        "926F5B" => [ "name" => "Beaver"],
        "928573" => [ "name" => "Stonewall"],
        "928590" => [ "name" => "Venus"],
        "9370DB" => [ "name" => "Medium Purple"],
        "93CCEA" => [ "name" => "Cornflower"],
        "93DFB8" => [ "name" => "Algae Green"],
        "944747" => [ "name" => "Copper Rust"],
        "948771" => [ "name" => "Arrowtown"],
        "950015" => [ "name" => "Scarlett"],
        "956387" => [ "name" => "Strikemaster"],
        "959396" => [ "name" => "Mountain Mist"],
        "960018" => [ "name" => "Carmine"],
        "964B00" => [ "name" => "Brown"],
        "967059" => [ "name" => "Leather"],
        "9678B6" => [ "name" => "Purple Mountain's Majesty"],
        "967BB6" => [ "name" => "Lavender Purple"],
        "96A8A1" => [ "name" => "Pewter"],
        "96BBAB" => [ "name" => "Summer Green"],
        "97605D" => [ "name" => "Au Chico"],
        "9771B5" => [ "name" => "Wisteria"],
        "97CD2D" => [ "name" => "Atlantis"],
        "983D61" => [ "name" => "Vin Rouge"],
        "9874D3" => [ "name" => "Lilac Bush"],
        "98777B" => [ "name" => "Bazaar"],
        "98811B" => [ "name" => "Hacienda"],
        "988D77" => [ "name" => "Pale Oyster"],
        "98FF98" => [ "name" => "Mint Green"],
        "990066" => [ "name" => "Fresh Eggplant"],
        "991199" => [ "name" => "Violet Eggplant"],
        "991613" => [ "name" => "Tamarillo"],
        "991B07" => [ "name" => "Totem Pole"],
        "996666" => [ "name" => "Copper Rose"],
        "9966CC" => [ "name" => "Amethyst"],
        "997A8D" => [ "name" => "Mountbatten Pink"],
        "9999CC" => [ "name" => "Blue Bell"],
        "9A3820" => [ "name" => "Prairie Sand"],
        "9A6E61" => [ "name" => "Toast"],
        "9A9577" => [ "name" => "Gurkha"],
        "9AB973" => [ "name" => "Olivine"],
        "9AC2B8" => [ "name" => "Shadow Green"],
        "9B4703" => [ "name" => "Oregon"],
        "9B9E8F" => [ "name" => "Lemon Grass"],
        "9C3336" => [ "name" => "Stiletto"],
        "9D5616" => [ "name" => "Hawaiian Tan"],
        "9DACB7" => [ "name" => "Gull Gray"],
        "9DC209" => [ "name" => "Pistachio"],
        "9DE093" => [ "name" => "Granny Smith Apple"],
        "9DE5FF" => [ "name" => "Anakiwa"],
        "9E5302" => [ "name" => "Chelsea Gem"],
        "9E5B40" => [ "name" => "Sepia Skin"],
        "9EA587" => [ "name" => "Sage"],
        "9EA91F" => [ "name" => "Citron"],
        "9EB1CD" => [ "name" => "Rock Blue"],
        "9EDEE0" => [ "name" => "Morning Glory"],
        "9F381D" => [ "name" => "Cognac"],
        "9F821C" => [ "name" => "Reef Gold"],
        "9F9F9C" => [ "name" => "Star Dust"],
        "9FA0B1" => [ "name" => "Santas Gray"],
        "9FD7D3" => [ "name" => "Sinbad"],
        "9FDD8C" => [ "name" => "Feijoa"],
        "A02712" => [ "name" => "Tabasco"],
        "A1750D" => [ "name" => "Buttered Rum"],
        "A1ADB5" => [ "name" => "Hit Gray"],
        "A1C50A" => [ "name" => "Citrus"],
        "A1DAD7" => [ "name" => "Aqua Island"],
        "A1E9DE" => [ "name" => "Water Leaf"],
        "A2006D" => [ "name" => "Flirt"],
        "A23B6C" => [ "name" => "Rouge"],
        "A26645" => [ "name" => "Cape Palliser"],
        "A2AAB3" => [ "name" => "Gray Chateau"],
        "A2AEAB" => [ "name" => "Edward"],
        "A3807B" => [ "name" => "Pharlap"],
        "A397B4" => [ "name" => "Amethyst Smoke"],
        "A3E3ED" => [ "name" => "Blizzard Blue"],
        "A4A49D" => [ "name" => "Delta"],
        "A4A6D3" => [ "name" => "Wistful"],
        "A4AF6E" => [ "name" => "Green Smoke"],
        "A50B5E" => [ "name" => "Jazzberry Jam"],
        "A59B91" => [ "name" => "Zorba"],
        "A5CB0C" => [ "name" => "Bahia"],
        "A62F20" => [ "name" => "Roof Terracotta"],
        "A65529" => [ "name" => "Paarl"],
        "A68B5B" => [ "name" => "Barley Corn"],
        "A69279" => [ "name" => "Donkey Brown"],
        "A6A29A" => [ "name" => "Dawn"],
        "A72525" => [ "name" => "Mexican Red"],
        "A7882C" => [ "name" => "Luxor Gold"],
        "A85307" => [ "name" => "Rich Gold"],
        "A86515" => [ "name" => "Reno Sand"],
        "A86B6B" => [ "name" => "Coral Tree"],
        "A8989B" => [ "name" => "Dusty Gray"],
        "A899E6" => [ "name" => "Dull Lavender"],
        "A8A589" => [ "name" => "Tallow"],
        "A8AE9C" => [ "name" => "Bud"],
        "A8AF8E" => [ "name" => "Locust"],
        "A8BD9F" => [ "name" => "Norway"],
        "A8E3BD" => [ "name" => "Chinook"],
        "A9A491" => [ "name" => "Gray Olive"],
        "A9ACB6" => [ "name" => "Aluminium"],
        "A9B2C3" => [ "name" => "Cadet Blue"],
        "A9B497" => [ "name" => "Schist"],
        "A9BDBF" => [ "name" => "Tower Gray"],
        "A9BEF2" => [ "name" => "Perano"],
        "A9C6C2" => [ "name" => "Opal"],
        "AA375A" => [ "name" => "Night Shadz"],
        "AA4203" => [ "name" => "Fire"],
        "AA8B5B" => [ "name" => "Muesli"],
        "AA8D6F" => [ "name" => "Sandal"],
        "AAA5A9" => [ "name" => "Shady Lady"],
        "AAA9CD" => [ "name" => "Logan"],
        "AAABB7" => [ "name" => "Spun Pearl"],
        "AAD6E6" => [ "name" => "Regent St Blue"],
        "AAF0D1" => [ "name" => "Magic Mint"],
        "AB0563" => [ "name" => "Lipstick"],
        "AB3472" => [ "name" => "Royal Heath"],
        "AB917A" => [ "name" => "Sandrift"],
        "ABA0D9" => [ "name" => "Cold Purple"],
        "ABA196" => [ "name" => "Bronco"],
        "AC8A56" => [ "name" => "Limed Oak"],
        "AC91CE" => [ "name" => "East Side"],
        "AC9E22" => [ "name" => "Lemon Ginger"],
        "ACA494" => [ "name" => "Napa"],
        "ACA586" => [ "name" => "Hillary"],
        "ACA59F" => [ "name" => "Cloudy"],
        "ACACAC" => [ "name" => "Silver Chalice"],
        "ACB78E" => [ "name" => "Swamp Green"],
        "ACCBB1" => [ "name" => "Spring Rain"],
        "ACDD4D" => [ "name" => "Conifer"],
        "ACE1AF" => [ "name" => "Celadon"],
        "AD781B" => [ "name" => "Mandalay"],
        "ADBED1" => [ "name" => "Casper"],
        "ADDFAD" => [ "name" => "Moss Green"],
        "ADE6C4" => [ "name" => "Padua"],
        "ADFF2F" => [ "name" => "Green Yellow"],
        "AE4560" => [ "name" => "Hippie Pink"],
        "AE6020" => [ "name" => "Desert"],
        "AE809E" => [ "name" => "Bouquet"],
        "AF4035" => [ "name" => "Medium Carmine"],
        "AF4D43" => [ "name" => "Apple Blossom"],
        "AF593E" => [ "name" => "Brown Rust"],
        "AF8751" => [ "name" => "Driftwood"],
        "AF8F2C" => [ "name" => "Alpine"],
        "AF9F1C" => [ "name" => "Lucky"],
        "AFA09E" => [ "name" => "Martini"],
        "AFB1B8" => [ "name" => "Bombay"],
        "AFBDD9" => [ "name" => "Pigeon Post"],
        "B04C6A" => [ "name" => "Cadillac"],
        "B05D54" => [ "name" => "Matrix"],
        "B05E81" => [ "name" => "Tapestry"],
        "B06608" => [ "name" => "Mai Tai"],
        "B09A95" => [ "name" => "Del Rio"],
        "B0E0E6" => [ "name" => "Powder Blue"],
        "B0E313" => [ "name" => "Inch Worm"],
        "B10000" => [ "name" => "Bright Red"],
        "B14A0B" => [ "name" => "Vesuvius"],
        "B1610B" => [ "name" => "Pumpkin Skin"],
        "B16D52" => [ "name" => "Santa Fe"],
        "B19461" => [ "name" => "Teak"],
        "B1E2C1" => [ "name" => "Fringy Flower"],
        "B1F4E7" => [ "name" => "Ice Cold"],
        "B20931" => [ "name" => "Shiraz"],
        "B2A1EA" => [ "name" => "Biloba Flower"],
        "B32D29" => [ "name" => "Tall Poppy"],
        "B35213" => [ "name" => "Fiery Orange"],
        "B38007" => [ "name" => "Hot Toddy"],
        "B3AF95" => [ "name" => "Taupe Gray"],
        "B3C110" => [ "name" => "La Rioja"],
        "B43332" => [ "name" => "Well Read"],
        "B44668" => [ "name" => "Blush"],
        "B4CFD3" => [ "name" => "Jungle Mist"],
        "B57281" => [ "name" => "Turkish Rose"],
        "B57EDC" => [ "name" => "Lavender"],
        "B5A27F" => [ "name" => "Mongoose"],
        "B5B35C" => [ "name" => "Olive Green"],
        "B5D2CE" => [ "name" => "Jet Stream"],
        "B5ECDF" => [ "name" => "Cruise"],
        "B6316C" => [ "name" => "Hibiscus"],
        "B69D98" => [ "name" => "Thatch"],
        "B6B095" => [ "name" => "Heathered Gray"],
        "B6BAA4" => [ "name" => "Eagle"],
        "B6D1EA" => [ "name" => "Spindle"],
        "B6D3BF" => [ "name" => "Gum Leaf"],
        "B7410E" => [ "name" => "Rust"],
        "B78E5C" => [ "name" => "Muddy Waters"],
        "B7A214" => [ "name" => "Sahara"],
        "B7A458" => [ "name" => "Husk"],
        "B7B1B1" => [ "name" => "Nobel"],
        "B7C3D0" => [ "name" => "Heather"],
        "B7F0BE" => [ "name" => "Madang"],
        "B81104" => [ "name" => "Milano Red"],
        "B87333" => [ "name" => "Copper"],
        "B8B56A" => [ "name" => "Gimblet"],
        "B8C1B1" => [ "name" => "Green Spring"],
        "B8C25D" => [ "name" => "Celery"],
        "B8E0F9" => [ "name" => "Sail"],
        "B94E48" => [ "name" => "Chestnut"],
        "B95140" => [ "name" => "Crail"],
        "B98D28" => [ "name" => "Marigold"],
        "B9C46A" => [ "name" => "Wild Willow"],
        "B9C8AC" => [ "name" => "Rainee"],
        "BA0101" => [ "name" => "Guardsman Red"],
        "BA450C" => [ "name" => "Rock Spray"],
        "BA6F1E" => [ "name" => "Bourbon"],
        "BA7F03" => [ "name" => "Pirate Gold"],
        "BAB1A2" => [ "name" => "Nomad"],
        "BAC7C9" => [ "name" => "Submarine"],
        "BAEEF9" => [ "name" => "Charlotte"],
        "BB3385" => [ "name" => "Medium Red Violet"],
        "BB8983" => [ "name" => "Brandy Rose"],
        "BBD009" => [ "name" => "Rio Grande"],
        "BBD7C1" => [ "name" => "Surf"],
        "BCC9C2" => [ "name" => "Powder Ash"],
        "BD5E2E" => [ "name" => "Tuscany"],
        "BD978E" => [ "name" => "Quicksand"],
        "BDB1A8" => [ "name" => "Silk"],
        "BDB2A1" => [ "name" => "Malta"],
        "BDB3C7" => [ "name" => "Chatelle"],
        "BDBBD7" => [ "name" => "Lavender Gray"],
        "BDBDC6" => [ "name" => "French Gray"],
        "BDC8B3" => [ "name" => "Clay Ash"],
        "BDC9CE" => [ "name" => "Loblolly"],
        "BDEDFD" => [ "name" => "French Pass"],
        "BEA6C3" => [ "name" => "London Hue"],
        "BEB5B7" => [ "name" => "Pink Swan"],
        "BEDE0D" => [ "name" => "Fuego"],
        "BF5500" => [ "name" => "Rose of Sharon"],
        "BFB8B0" => [ "name" => "Tide"],
        "BFBED8" => [ "name" => "Blue Haze"],
        "BFC1C2" => [ "name" => "Silver Sand"],
        "BFC921" => [ "name" => "Key Lime Pie"],
        "BFDBE2" => [ "name" => "Ziggurat"],
        "BFFF00" => [ "name" => "Lime"],
        "C02B18" => [ "name" => "Thunderbird"],
        "C04737" => [ "name" => "Mojo"],
        "C08081" => [ "name" => "Old Rose"],
        "C0C0C0" => [ "name" => "Silver"],
        "C0D3B9" => [ "name" => "Pale Leaf"],
        "C0D8B6" => [ "name" => "Pixie Green"],
        "C1440E" => [ "name" => "Tia Maria"],
        "C154C1" => [ "name" => "Fuchsia Pink"],
        "C1A004" => [ "name" => "Buddha Gold"],
        "C1B7A4" => [ "name" => "Bison Hide"],
        "C1BAB0" => [ "name" => "Tea"],
        "C1BECD" => [ "name" => "Gray Suit"],
        "C1D7B0" => [ "name" => "Sprout"],
        "C1F07C" => [ "name" => "Sulu"],
        "C26B03" => [ "name" => "Indochine"],
        "C2955D" => [ "name" => "Twine"],
        "C2BDB6" => [ "name" => "Cotton Seed"],
        "C2CAC4" => [ "name" => "Pumice"],
        "C2E8E5" => [ "name" => "Jagged Ice"],
        "C32148" => [ "name" => "Maroon Flush"],
        "C3B091" => [ "name" => "Indian Khaki"],
        "C3BFC1" => [ "name" => "Pale Slate"],
        "C3C3BD" => [ "name" => "Gray Nickel"],
        "C3CDE6" => [ "name" => "Periwinkle Gray"],
        "C3D1D1" => [ "name" => "Tiara"],
        "C3DDF9" => [ "name" => "Tropical Blue"],
        "C41E3A" => [ "name" => "Cardinal"],
        "C45655" => [ "name" => "Fuzzy Wuzzy Brown"],
        "C45719" => [ "name" => "Orange Roughy"],
        "C4C4BC" => [ "name" => "Mist Gray"],
        "C4D0B0" => [ "name" => "Coriander"],
        "C4F4EB" => [ "name" => "Mint Tulip"],
        "C54B8C" => [ "name" => "Mulberry"],
        "C59922" => [ "name" => "Nugget"],
        "C5994B" => [ "name" => "Tussock"],
        "C5DBCA" => [ "name" => "Sea Mist"],
        "C5E17A" => [ "name" => "Yellow Green"],
        "C62D42" => [ "name" => "Brick Red"],
        "C6726B" => [ "name" => "Contessa"],
        "C69191" => [ "name" => "Oriental Pink"],
        "C6A84B" => [ "name" => "Roti"],
        "C6C3B5" => [ "name" => "Ash"],
        "C6C8BD" => [ "name" => "Kangaroo"],
        "C6E610" => [ "name" => "Las Palmas"],
        "C7031E" => [ "name" => "Monza"],
        "C71585" => [ "name" => "Red Violet"],
        "C7BCA2" => [ "name" => "Coral Reef"],
        "C7C1FF" => [ "name" => "Melrose"],
        "C7C4BF" => [ "name" => "Cloud"],
        "C7C9D5" => [ "name" => "Ghost"],
        "C7CD90" => [ "name" => "Pine Glade"],
        "C7DDE5" => [ "name" => "Botticelli"],
        "C88A65" => [ "name" => "Antique Brass"],
        "C8A2C8" => [ "name" => "Lilac"],
        "C8A528" => [ "name" => "Hokey Pokey"],
        "C8AABF" => [ "name" => "Lily"],
        "C8B568" => [ "name" => "Laser"],
        "C8E3D7" => [ "name" => "Edgewater"],
        "C96323" => [ "name" => "Piper"],
        "C99415" => [ "name" => "Pizza"],
        "C9A0DC" => [ "name" => "Light Wisteria"],
        "C9B29B" => [ "name" => "Rodeo Dust"],
        "C9B35B" => [ "name" => "Sundance"],
        "C9B93B" => [ "name" => "Earls Green"],
        "C9C0BB" => [ "name" => "Silver Rust"],
        "C9D9D2" => [ "name" => "Conch"],
        "C9FFA2" => [ "name" => "Reef"],
        "C9FFE5" => [ "name" => "Aero Blue"],
        "CA3435" => [ "name" => "Flush Mahogany"],
        "CABB48" => [ "name" => "Turmeric"],
        "CADCD4" => [ "name" => "Paris White"],
        "CAE00D" => [ "name" => "Bitter Lemon"],
        "CAE6DA" => [ "name" => "Skeptic"],
        "CB8FA9" => [ "name" => "Viola"],
        "CBCAB6" => [ "name" => "Foggy Gray"],
        "CBD3B0" => [ "name" => "Green Mist"],
        "CBDBD6" => [ "name" => "Nebula"],
        "CC3333" => [ "name" => "Persian Red"],
        "CC5500" => [ "name" => "Burnt Orange"],
        "CC7722" => [ "name" => "Ochre"],
        "CC8899" => [ "name" => "Puce"],
        "CCCAA8" => [ "name" => "Thistle Green"],
        "CCCCFF" => [ "name" => "Periwinkle"],
        "CCFF00" => [ "name" => "Electric Lime"],
        "CD5700" => [ "name" => "Tenn"],
        "CD5C5C" => [ "name" => "Chestnut Rose"],
        "CD8429" => [ "name" => "Brandy Punch"],
        "CDF4FF" => [ "name" => "Onahau"],
        "CEB98F" => [ "name" => "Sorrell Brown"],
        "CEBABA" => [ "name" => "Cold Turkey"],
        "CEC291" => [ "name" => "Yuma"],
        "CEC7A7" => [ "name" => "Chino"],
        "CFA39D" => [ "name" => "Eunry"],
        "CFB53B" => [ "name" => "Old Gold"],
        "CFDCCF" => [ "name" => "Tasman"],
        "CFE5D2" => [ "name" => "Surf Crest"],
        "CFF9F3" => [ "name" => "Humming Bird"],
        "CFFAF4" => [ "name" => "Scandal"],
        "D05F04" => [ "name" => "Red Stage"],
        "D06DA1" => [ "name" => "Hopbush"],
        "D07D12" => [ "name" => "Meteor"],
        "D0BEF8" => [ "name" => "Perfume"],
        "D0C0E5" => [ "name" => "Prelude"],
        "D0F0C0" => [ "name" => "Tea Green"],
        "D18F1B" => [ "name" => "Geebung"],
        "D1BEA8" => [ "name" => "Vanilla"],
        "D1C6B4" => [ "name" => "Soft Amber"],
        "D1D2CA" => [ "name" => "Celeste"],
        "D1D2DD" => [ "name" => "Mischka"],
        "D1E231" => [ "name" => "Pear"],
        "D2691E" => [ "name" => "Hot Cinnamon"],
        "D27D46" => [ "name" => "Raw Sienna"],
        "D29EAA" => [ "name" => "Careys Pink"],
        "D2B48C" => [ "name" => "Tan"],
        "D2DA97" => [ "name" => "Deco"],
        "D2F6DE" => [ "name" => "Blue Romance"],
        "D2F8B0" => [ "name" => "Gossip"],
        "D3CBBA" => [ "name" => "Sisal"],
        "D3CDC5" => [ "name" => "Swirl"],
        "D47494" => [ "name" => "Charm"],
        "D4B6AF" => [ "name" => "Clam Shell"],
        "D4BF8D" => [ "name" => "Straw"],
        "D4C4A8" => [ "name" => "Akaroa"],
        "D4CD16" => [ "name" => "Bird Flower"],
        "D4D7D9" => [ "name" => "Iron"],
        "D4DFE2" => [ "name" => "Geyser"],
        "D4E2FC" => [ "name" => "Hawkes Blue"],
        "D54600" => [ "name" => "Grenadier"],
        "D591A4" => [ "name" => "Can Can"],
        "D59A6F" => [ "name" => "Whiskey"],
        "D5D195" => [ "name" => "Winter Hazel"],
        "D5F6E3" => [ "name" => "Granny Apple"],
        "D69188" => [ "name" => "My Pink"],
        "D6C562" => [ "name" => "Tacha"],
        "D6CEF6" => [ "name" => "Moon Raker"],
        "D6D6D1" => [ "name" => "Quill Gray"],
        "D6FFDB" => [ "name" => "Snowy Mint"],
        "D7837F" => [ "name" => "New York Pink"],
        "D7C498" => [ "name" => "Pavlova"],
        "D7D0FF" => [ "name" => "Fog"],
        "D84437" => [ "name" => "Valencia"],
        "D87C63" => [ "name" => "Japonica"],
        "D8BFD8" => [ "name" => "Thistle"],
        "D8C2D5" => [ "name" => "Maverick"],
        "D8FCFA" => [ "name" => "Foam"],
        "D94972" => [ "name" => "Cabaret"],
        "D99376" => [ "name" => "Burning Sand"],
        "D9B99B" => [ "name" => "Cameo"],
        "D9D6CF" => [ "name" => "Timberwolf"],
        "D9DCC1" => [ "name" => "Tana"],
        "D9E4F5" => [ "name" => "Link Water"],
        "D9F7FF" => [ "name" => "Mabel"],
        "DA3287" => [ "name" => "Cerise"],
        "DA5B38" => [ "name" => "Flame Pea"],
        "DA6304" => [ "name" => "Bamboo"],
        "DA6A41" => [ "name" => "Red Damask"],
        "DA70D6" => [ "name" => "Orchid"],
        "DA8A67" => [ "name" => "Copperfield"],
        "DAA520" => [ "name" => "Golden Grass"],
        "DAECD6" => [ "name" => "Zanah"],
        "DAF4F0" => [ "name" => "Iceberg"],
        "DAFAFF" => [ "name" => "Oyster Bay"],
        "DB5079" => [ "name" => "Cranberry"],
        "DB9690" => [ "name" => "Petite Orchid"],
        "DB995E" => [ "name" => "Di Serria"],
        "DBDBDB" => [ "name" => "Alto"],
        "DBFFF8" => [ "name" => "Frosted Mint"],
        "DC143C" => [ "name" => "Crimson"],
        "DC4333" => [ "name" => "Punch"],
        "DCB20C" => [ "name" => "Galliano"],
        "DCB4BC" => [ "name" => "Blossom"],
        "DCD747" => [ "name" => "Wattle"],
        "DCD9D2" => [ "name" => "Westar"],
        "DCDDCC" => [ "name" => "Moon Mist"],
        "DCEDB4" => [ "name" => "Caper"],
        "DCF0EA" => [ "name" => "Swans Down"],
        "DDD6D5" => [ "name" => "Swiss Coffee"],
        "DDF9F1" => [ "name" => "White Ice"],
        "DE3163" => [ "name" => "Cerise Red"],
        "DE6360" => [ "name" => "Roman"],
        "DEA681" => [ "name" => "Tumbleweed"],
        "DEBA13" => [ "name" => "Gold Tips"],
        "DEC196" => [ "name" => "Brandy"],
        "DECBC6" => [ "name" => "Wafer"],
        "DED4A4" => [ "name" => "Sapling"],
        "DED717" => [ "name" => "Barberry"],
        "DEE5C0" => [ "name" => "Beryl Green"],
        "DEF5FF" => [ "name" => "Pattens Blue"],
        "DF73FF" => [ "name" => "Heliotrope"],
        "DFBE6F" => [ "name" => "Apache"],
        "DFCD6F" => [ "name" => "Chenin"],
        "DFCFDB" => [ "name" => "Lola"],
        "DFECDA" => [ "name" => "Willow Brook"],
        "DFFF00" => [ "name" => "Chartreuse Yellow"],
        "E0B0FF" => [ "name" => "Mauve"],
        "E0B646" => [ "name" => "Anzac"],
        "E0B974" => [ "name" => "Harvest Gold"],
        "E0C095" => [ "name" => "Calico"],
        "E0FFFF" => [ "name" => "Baby Blue"],
        "E16865" => [ "name" => "Sunglo"],
        "E1BC64" => [ "name" => "Equator"],
        "E1C0C8" => [ "name" => "Pink Flare"],
        "E1E6D6" => [ "name" => "Periglacial Blue"],
        "E1EAD4" => [ "name" => "Kidnapper"],
        "E1F6E8" => [ "name" => "Tara"],
        "E25465" => [ "name" => "Mandy"],
        "E2725B" => [ "name" => "Terracotta"],
        "E28913" => [ "name" => "Golden Bell"],
        "E292C0" => [ "name" => "Shocking"],
        "E29418" => [ "name" => "Dixie"],
        "E29CD2" => [ "name" => "Light Orchid"],
        "E2D8ED" => [ "name" => "Snuff"],
        "E2EBED" => [ "name" => "Mystic"],
        "E2F3EC" => [ "name" => "Apple Green"],
        "E30B5C" => [ "name" => "Razzmatazz"],
        "E32636" => [ "name" => "Alizarin Crimson"],
        "E34234" => [ "name" => "Cinnabar"],
        "E3BEBE" => [ "name" => "Cavern Pink"],
        "E3F5E1" => [ "name" => "Peppermint"],
        "E3F988" => [ "name" => "Mindaro"],
        "E47698" => [ "name" => "Deep Blush"],
        "E49B0F" => [ "name" => "Gamboge"],
        "E4C2D5" => [ "name" => "Melanie"],
        "E4CFDE" => [ "name" => "Twilight"],
        "E4D1C0" => [ "name" => "Bone"],
        "E4D422" => [ "name" => "Sunflower"],
        "E4D5B7" => [ "name" => "Grain Brown"],
        "E4D69B" => [ "name" => "Zombie"],
        "E4F6E7" => [ "name" => "Frostee"],
        "E4FFD1" => [ "name" => "Snow Flurry"],
        "E52B50" => [ "name" => "Amaranth"],
        "E5841B" => [ "name" => "Zest"],
        "E5CCC9" => [ "name" => "Dust Storm"],
        "E5D7BD" => [ "name" => "Stark White"],
        "E5D8AF" => [ "name" => "Hampton"],
        "E5E0E1" => [ "name" => "Bon Jour"],
        "E5E5E5" => [ "name" => "Mercury"],
        "E5F9F6" => [ "name" => "Polar"],
        "E64E03" => [ "name" => "Trinidad"],
        "E6BE8A" => [ "name" => "Gold Sand"],
        "E6BEA5" => [ "name" => "Cashmere"],
        "E6D7B9" => [ "name" => "Double Spanish White"],
        "E6E4D4" => [ "name" => "Satin Linen"],
        "E6F2EA" => [ "name" => "Harp"],
        "E6F8F3" => [ "name" => "Off Green"],
        "E6FFE9" => [ "name" => "Hint of Green"],
        "E6FFFF" => [ "name" => "Tranquil"],
        "E77200" => [ "name" => "Mango Tango"],
        "E7730A" => [ "name" => "Christine"],
        "E79F8C" => [ "name" => "Tonys Pink"],
        "E79FC4" => [ "name" => "Kobi"],
        "E7BCB4" => [ "name" => "Rose Fog"],
        "E7BF05" => [ "name" => "Corn"],
        "E7CD8C" => [ "name" => "Putty"],
        "E7ECE6" => [ "name" => "Gray Nurse"],
        "E7F8FF" => [ "name" => "Lily White"],
        "E7FEFF" => [ "name" => "Bubbles"],
        "E89928" => [ "name" => "Fire Bush"],
        "E8B9B3" => [ "name" => "Shilo"],
        "E8E0D5" => [ "name" => "Pearl Bush"],
        "E8EBE0" => [ "name" => "Green White"],
        "E8F1D4" => [ "name" => "Chrome White"],
        "E8F2EB" => [ "name" => "Gin"],
        "E8F5F2" => [ "name" => "Aqua Squeeze"],
        "E96E00" => [ "name" => "Clementine"],
        "E97451" => [ "name" => "Burnt Sienna"],
        "E97C07" => [ "name" => "Tahiti Gold"],
        "E9CECD" => [ "name" => "Oyster Pink"],
        "E9D75A" => [ "name" => "Confetti"],
        "E9E3E3" => [ "name" => "Ebb"],
        "E9F8ED" => [ "name" => "Ottoman"],
        "E9FFFD" => [ "name" => "Clear Day"],
        "EA88A8" => [ "name" => "Carissma"],
        "EAAE69" => [ "name" => "Porsche"],
        "EAB33B" => [ "name" => "Tulip Tree"],
        "EAC674" => [ "name" => "Rob Roy"],
        "EADAB8" => [ "name" => "Raffia"],
        "EAE8D4" => [ "name" => "White Rock"],
        "EAF6EE" => [ "name" => "Panache"],
        "EAF6FF" => [ "name" => "Solitude"],
        "EAF9F5" => [ "name" => "Aqua Spring"],
        "EAFFFE" => [ "name" => "Dew"],
        "EB9373" => [ "name" => "Apricot"],
        "EBC2AF" => [ "name" => "Zinnwaldite"],
        "ECA927" => [ "name" => "Fuel Yellow"],
        "ECC54E" => [ "name" => "Ronchi"],
        "ECC7EE" => [ "name" => "French Lilac"],
        "ECCDB9" => [ "name" => "Just Right"],
        "ECE090" => [ "name" => "Wild Rice"],
        "ECEBBD" => [ "name" => "Fall Green"],
        "ECEBCE" => [ "name" => "Aths Special"],
        "ECF245" => [ "name" => "Starship"],
        "ED0A3F" => [ "name" => "Red Ribbon"],
        "ED7A1C" => [ "name" => "Tango"],
        "ED9121" => [ "name" => "Carrot Orange"],
        "ED989E" => [ "name" => "Sea Pink"],
        "EDB381" => [ "name" => "Tacao"],
        "EDC9AF" => [ "name" => "Desert Sand"],
        "EDCDAB" => [ "name" => "Pancho"],
        "EDDCB1" => [ "name" => "Chamois"],
        "EDEA99" => [ "name" => "Primrose"],
        "EDF5DD" => [ "name" => "Frost"],
        "EDF5F5" => [ "name" => "Aqua Haze"],
        "EDF6FF" => [ "name" => "Zumthor"],
        "EDF9F1" => [ "name" => "Narvik"],
        "EDFC84" => [ "name" => "Honeysuckle"],
        "EE82EE" => [ "name" => "Lavender Magenta"],
        "EEC1BE" => [ "name" => "Beauty Bush"],
        "EED794" => [ "name" => "Chalky"],
        "EED9C4" => [ "name" => "Almond"],
        "EEDC82" => [ "name" => "Flax"],
        "EEDEDA" => [ "name" => "Bizarre"],
        "EEE3AD" => [ "name" => "Double Colonial White"],
        "EEEEE8" => [ "name" => "Cararra"],
        "EEEF78" => [ "name" => "Manz"],
        "EEF0C8" => [ "name" => "Tahuna Sands"],
        "EEF0F3" => [ "name" => "Athens Gray"],
        "EEF3C3" => [ "name" => "Tusk"],
        "EEF4DE" => [ "name" => "Loafer"],
        "EEF6F7" => [ "name" => "Catskill White"],
        "EEFDFF" => [ "name" => "Twilight Blue"],
        "EEFF9A" => [ "name" => "Jonquil"],
        "EEFFE2" => [ "name" => "Rice Flower"],
        "EF863F" => [ "name" => "Jaffa"],
        "EFEFEF" => [ "name" => "Gallery"],
        "EFF2F3" => [ "name" => "Porcelain"],
        "F091A9" => [ "name" => "Mauvelous"],
        "F0D52D" => [ "name" => "Golden Dream"],
        "F0DB7D" => [ "name" => "Golden Sand"],
        "F0DC82" => [ "name" => "Buff"],
        "F0E2EC" => [ "name" => "Prim"],
        "F0E68C" => [ "name" => "Khaki"],
        "F0EEFD" => [ "name" => "Selago"],
        "F0EEFF" => [ "name" => "Titan White"],
        "F0F8FF" => [ "name" => "Alice Blue"],
        "F0FCEA" => [ "name" => "Feta"],
        "F18200" => [ "name" => "Gold Drop"],
        "F19BAB" => [ "name" => "Wewak"],
        "F1E788" => [ "name" => "Sahara Sand"],
        "F1E9D2" => [ "name" => "Parchment"],
        "F1E9FF" => [ "name" => "Blue Chalk"],
        "F1EEC1" => [ "name" => "Mint Julep"],
        "F1F1F1" => [ "name" => "Seashell"],
        "F1F7F2" => [ "name" => "Saltpan"],
        "F1FFAD" => [ "name" => "Tidal"],
        "F1FFC8" => [ "name" => "Chiffon"],
        "F2552A" => [ "name" => "Flamingo"],
        "F28500" => [ "name" => "Tangerine"],
        "F2C3B2" => [ "name" => "Mandys Pink"],
        "F2F2F2" => [ "name" => "Concrete"],
        "F2FAFA" => [ "name" => "Black Squeeze"],
        "F34723" => [ "name" => "Pomegranate"],
        "F3AD16" => [ "name" => "Buttercup"],
        "F3D69D" => [ "name" => "New Orleans"],
        "F3D9DF" => [ "name" => "Vanilla Ice"],
        "F3E7BB" => [ "name" => "Sidecar"],
        "F3E9E5" => [ "name" => "Dawn Pink"],
        "F3EDCF" => [ "name" => "Wheatfield"],
        "F3FB62" => [ "name" => "Canary"],
        "F3FBD4" => [ "name" => "Orinoco"],
        "F3FFD8" => [ "name" => "Carla"],
        "F400A1" => [ "name" => "Hollywood Cerise"],
        "F4A460" => [ "name" => "Sandy brown"],
        "F4C430" => [ "name" => "Saffron"],
        "F4D81C" => [ "name" => "Ripe Lemon"],
        "F4EBD3" => [ "name" => "Janna"],
        "F4F2EE" => [ "name" => "Pampas"],
        "F4F4F4" => [ "name" => "Wild Sand"],
        "F4F8FF" => [ "name" => "Zircon"],
        "F57584" => [ "name" => "Froly"],
        "F5C85C" => [ "name" => "Cream Can"],
        "F5C999" => [ "name" => "Manhattan"],
        "F5D5A0" => [ "name" => "Maize"],
        "F5DEB3" => [ "name" => "Wheat"],
        "F5E7A2" => [ "name" => "Sandwisp"],
        "F5E7E2" => [ "name" => "Pot Pourri"],
        "F5E9D3" => [ "name" => "Albescent White"],
        "F5EDEF" => [ "name" => "Soft Peach"],
        "F5F3E5" => [ "name" => "Ecru White"],
        "F5F5DC" => [ "name" => "Beige"],
        "F5FB3D" => [ "name" => "Golden Fizz"],
        "F5FFBE" => [ "name" => "Australian Mint"],
        "F64A8A" => [ "name" => "French Rose"],
        "F653A6" => [ "name" => "Brilliant Rose"],
        "F6A4C9" => [ "name" => "Illusion"],
        "F6F0E6" => [ "name" => "Merino"],
        "F6F7F7" => [ "name" => "Black Haze"],
        "F6FFDC" => [ "name" => "Spring Sun"],
        "F7468A" => [ "name" => "Violet Red"],
        "F77703" => [ "name" => "Chilean Fire"],
        "F77FBE" => [ "name" => "Persian Pink"],
        "F7B668" => [ "name" => "Rajah"],
        "F7C8DA" => [ "name" => "Azalea"],
        "F7DBE6" => [ "name" => "We Peep"],
        "F7F2E1" => [ "name" => "Quarter Spanish White"],
        "F7F5FA" => [ "name" => "Whisper"],
        "F7FAF7" => [ "name" => "Snow Drift"],
        "F8B853" => [ "name" => "Casablanca"],
        "F8C3DF" => [ "name" => "Chantilly"],
        "F8D9E9" => [ "name" => "Cherub"],
        "F8DB9D" => [ "name" => "Marzipan"],
        "F8DD5C" => [ "name" => "Energy Yellow"],
        "F8E4BF" => [ "name" => "Givry"],
        "F8F0E8" => [ "name" => "White Linen"],
        "F8F4FF" => [ "name" => "Magnolia"],
        "F8F6F1" => [ "name" => "Spring Wood"],
        "F8F7DC" => [ "name" => "Coconut Cream"],
        "F8F7FC" => [ "name" => "White Lilac"],
        "F8F8F7" => [ "name" => "Desert Storm"],
        "F8F99C" => [ "name" => "Texas"],
        "F8FACD" => [ "name" => "Corn Field"],
        "F8FDD3" => [ "name" => "Mimosa"],
        "F95A61" => [ "name" => "Carnation"],
        "F9BF58" => [ "name" => "Saffron Mango"],
        "F9E0ED" => [ "name" => "Carousel Pink"],
        "F9E4BC" => [ "name" => "Dairy Cream"],
        "F9E663" => [ "name" => "Portica"],
        "F9EAF3" => [ "name" => "Amour"],
        "F9F8E4" => [ "name" => "Rum Swizzle"],
        "F9FF8B" => [ "name" => "Dolly"],
        "F9FFF6" => [ "name" => "Sugar Cane"],
        "FA7814" => [ "name" => "Ecstasy"],
        "FA9D5A" => [ "name" => "Tan Hide"],
        "FAD3A2" => [ "name" => "Corvette"],
        "FADFAD" => [ "name" => "Peach Yellow"],
        "FAE600" => [ "name" => "Turbo"],
        "FAEAB9" => [ "name" => "Astra"],
        "FAECCC" => [ "name" => "Champagne"],
        "FAF0E6" => [ "name" => "Linen"],
        "FAF3F0" => [ "name" => "Fantasy"],
        "FAF7D6" => [ "name" => "Citrine White"],
        "FAFAFA" => [ "name" => "Alabaster"],
        "FAFDE4" => [ "name" => "Hint of Yellow"],
        "FAFFA4" => [ "name" => "Milan"],
        "FB607F" => [ "name" => "Brink Pink"],
        "FB8989" => [ "name" => "Geraldine"],
        "FBA0E3" => [ "name" => "Lavender Rose"],
        "FBA129" => [ "name" => "Sea Buckthorn"],
        "FBAC13" => [ "name" => "Sun"],
        "FBAED2" => [ "name" => "Lavender Pink"],
        "FBB2A3" => [ "name" => "Rose Bud"],
        "FBBEDA" => [ "name" => "Cupid"],
        "FBCCE7" => [ "name" => "Classic Rose"],
        "FBCEB1" => [ "name" => "Apricot Peach"],
        "FBE7B2" => [ "name" => "Banana Mania"],
        "FBE870" => [ "name" => "Marigold Yellow"],
        "FBE96C" => [ "name" => "Festival"],
        "FBEA8C" => [ "name" => "Sweet Corn"],
        "FBEC5D" => [ "name" => "Candy Corn"],
        "FBF9F9" => [ "name" => "Hint of Red"],
        "FBFFBA" => [ "name" => "Shalimar"],
        "FC0FC0" => [ "name" => "Shocking Pink"],
        "FC80A5" => [ "name" => "Tickle Me Pink"],
        "FC9C1D" => [ "name" => "Tree Poppy"],
        "FCC01E" => [ "name" => "Lightning Yellow"],
        "FCD667" => [ "name" => "Goldenrod"],
        "FCD917" => [ "name" => "Candlelight"],
        "FCDA98" => [ "name" => "Cherokee"],
        "FCF4D0" => [ "name" => "Double Pearl Lusta"],
        "FCF4DC" => [ "name" => "Pearl Lusta"],
        "FCF8F7" => [ "name" => "Vista White"],
        "FCFBF3" => [ "name" => "Bianca"],
        "FCFEDA" => [ "name" => "Moon Glow"],
        "FCFFE7" => [ "name" => "China Ivory"],
        "FCFFF9" => [ "name" => "Ceramic"],
        "FD0E35" => [ "name" => "Torch Red"],
        "FD5B78" => [ "name" => "Wild Watermelon"],
        "FD7B33" => [ "name" => "Crusta"],
        "FD7C07" => [ "name" => "Sorbus"],
        "FD9FA2" => [ "name" => "Sweet Pink"],
        "FDD5B1" => [ "name" => "Light Apricot"],
        "FDD7E4" => [ "name" => "Pig Pink"],
        "FDE1DC" => [ "name" => "Cinderella"],
        "FDE295" => [ "name" => "Golden Glow"],
        "FDE910" => [ "name" => "Lemon"],
        "FDF5E6" => [ "name" => "Old Lace"],
        "FDF6D3" => [ "name" => "Half Colonial White"],
        "FDF7AD" => [ "name" => "Drover"],
        "FDFEB8" => [ "name" => "Pale Prim"],
        "FDFFD5" => [ "name" => "Cumulus"],
        "FE28A2" => [ "name" => "Persian Rose"],
        "FE4C40" => [ "name" => "Sunset Orange"],
        "FE6F5E" => [ "name" => "Bittersweet"],
        "FE9D04" => [ "name" => "California"],
        "FEA904" => [ "name" => "Yellow Sea"],
        "FEBAAD" => [ "name" => "Melon"],
        "FED33C" => [ "name" => "Bright Sun"],
        "FED85D" => [ "name" => "Dandelion"],
        "FEDB8D" => [ "name" => "Salomie"],
        "FEE5AC" => [ "name" => "Cape Honey"],
        "FEEBF3" => [ "name" => "Remy"],
        "FEEFCE" => [ "name" => "Oasis"],
        "FEF0EC" => [ "name" => "Bridesmaid"],
        "FEF2C7" => [ "name" => "Beeswax"],
        "FEF3D8" => [ "name" => "Bleach White"],
        "FEF4CC" => [ "name" => "Pipi"],
        "FEF4DB" => [ "name" => "Half Spanish White"],
        "FEF4F8" => [ "name" => "Wisp Pink"],
        "FEF5F1" => [ "name" => "Provincial Pink"],
        "FEF7DE" => [ "name" => "Half Dutch White"],
        "FEF8E2" => [ "name" => "Solitaire"],
        "FEF8FF" => [ "name" => "White Pointer"],
        "FEF9E3" => [ "name" => "Off Yellow"],
        "FEFCED" => [ "name" => "Orange White"],
        "FF0000" => [ "name" => "Red"],
        "FF007F" => [ "name" => "Rose"],
        "FF00CC" => [ "name" => "Purple Pizzazz"],
        "FF00FF" => [ "name" => "Magenta / Fuchsia"],
        "FF2400" => [ "name" => "Scarlet"],
        "FF3399" => [ "name" => "Wild Strawberry"],
        "FF33CC" => [ "name" => "Razzle Dazzle Rose"],
        "FF355E" => [ "name" => "Radical Red"],
        "FF3F34" => [ "name" => "Red Orange"],
        "FF4040" => [ "name" => "Coral Red"],
        "FF4D00" => [ "name" => "Vermilion"],
        "FF4F00" => [ "name" => "International Orange"],
        "FF6037" => [ "name" => "Outrageous Orange"],
        "FF6600" => [ "name" => "Blaze Orange"],
        "FF66FF" => [ "name" => "Pink Flamingo"],
        "FF681F" => [ "name" => "Orange"],
        "FF69B4" => [ "name" => "Hot Pink"],
        "FF6B53" => [ "name" => "Persimmon"],
        "FF6FFF" => [ "name" => "Blush Pink"],
        "FF7034" => [ "name" => "Burning Orange"],
        "FF7518" => [ "name" => "Pumpkin"],
        "FF7D07" => [ "name" => "Flamenco"],
        "FF7F00" => [ "name" => "Flush Orange"],
        "FF7F50" => [ "name" => "Coral"],
        "FF8C69" => [ "name" => "Salmon"],
        "FF9000" => [ "name" => "Pizazz"],
        "FF910F" => [ "name" => "West Side"],
        "FF91A4" => [ "name" => "Pink Salmon"],
        "FF9933" => [ "name" => "Neon Carrot"],
        "FF9966" => [ "name" => "Atomic Tangerine"],
        "FF9980" => [ "name" => "Vivid Tangerine"],
        "FF9E2C" => [ "name" => "Sunshade"],
        "FFA000" => [ "name" => "Orange Peel"],
        "FFA194" => [ "name" => "Mona Lisa"],
        "FFA500" => [ "name" => "Web Orange"],
        "FFA6C9" => [ "name" => "Carnation Pink"],
        "FFAB81" => [ "name" => "Hit Pink"],
        "FFAE42" => [ "name" => "Yellow Orange"],
        "FFB0AC" => [ "name" => "Cornflower Lilac"],
        "FFB1B3" => [ "name" => "Sundown"],
        "FFB31F" => [ "name" => "My Sin"],
        "FFB555" => [ "name" => "Texas Rose"],
        "FFB7D5" => [ "name" => "Cotton Candy"],
        "FFB97B" => [ "name" => "Macaroni and Cheese"],
        "FFBA00" => [ "name" => "Selective Yellow"],
        "FFBD5F" => [ "name" => "Koromiko"],
        "FFBF00" => [ "name" => "Amber"],
        "FFC0A8" => [ "name" => "Wax Flower"],
        "FFC0CB" => [ "name" => "Pink"],
        "FFC3C0" => [ "name" => "Your Pink"],
        "FFC901" => [ "name" => "Supernova"],
        "FFCBA4" => [ "name" => "Flesh"],
        "FFCC33" => [ "name" => "Sunglow"],
        "FFCC5C" => [ "name" => "Golden Tainoi"],
        "FFCC99" => [ "name" => "Peach Orange"],
        "FFCD8C" => [ "name" => "Chardonnay"],
        "FFD1DC" => [ "name" => "Pastel Pink"],
        "FFD2B7" => [ "name" => "Romantic"],
        "FFD38C" => [ "name" => "Grandis"],
        "FFD700" => [ "name" => "Gold"],
        "FFD800" => [ "name" => "School bus Yellow"],
        "FFD8D9" => [ "name" => "Cosmos"],
        "FFDB58" => [ "name" => "Mustard"],
        "FFDCD6" => [ "name" => "Peach Schnapps"],
        "FFDDAF" => [ "name" => "Caramel"],
        "FFDDCD" => [ "name" => "Tuft Bush"],
        "FFDDCF" => [ "name" => "Watusi"],
        "FFDDF4" => [ "name" => "Pink Lace"],
        "FFDEAD" => [ "name" => "Navajo White"],
        "FFDEB3" => [ "name" => "Frangipani"],
        "FFE1DF" => [ "name" => "Pippin"],
        "FFE1F2" => [ "name" => "Pale Rose"],
        "FFE2C5" => [ "name" => "Negroni"],
        "FFE5A0" => [ "name" => "Cream Brulee"],
        "FFE5B4" => [ "name" => "Peach"],
        "FFE6C7" => [ "name" => "Tequila"],
        "FFE772" => [ "name" => "Kournikova"],
        "FFEAC8" => [ "name" => "Sandy Beach"],
        "FFEAD4" => [ "name" => "Karry"],
        "FFEC13" => [ "name" => "Broom"],
        "FFEDBC" => [ "name" => "Colonial White"],
        "FFEED8" => [ "name" => "Derby"],
        "FFEFA1" => [ "name" => "Vis Vis"],
        "FFEFC1" => [ "name" => "Egg White"],
        "FFEFD5" => [ "name" => "Papaya Whip"],
        "FFEFEC" => [ "name" => "Fair Pink"],
        "FFF0DB" => [ "name" => "Peach Cream"],
        "FFF0F5" => [ "name" => "Lavender blush"],
        "FFF14F" => [ "name" => "Gorse"],
        "FFF1B5" => [ "name" => "Buttermilk"],
        "FFF1D8" => [ "name" => "Pink Lady"],
        "FFF1EE" => [ "name" => "Forget Me Not"],
        "FFF1F9" => [ "name" => "Tutu"],
        "FFF39D" => [ "name" => "Picasso"],
        "FFF3F1" => [ "name" => "Chardon"],
        "FFF46E" => [ "name" => "Paris Daisy"],
        "FFF4CE" => [ "name" => "Barley White"],
        "FFF4DD" => [ "name" => "Egg Sour"],
        "FFF4E0" => [ "name" => "Sazerac"],
        "FFF4E8" => [ "name" => "Serenade"],
        "FFF4F3" => [ "name" => "Chablis"],
        "FFF5EE" => [ "name" => "Seashell Peach"],
        "FFF5F3" => [ "name" => "Sauvignon"],
        "FFF6D4" => [ "name" => "Milk Punch"],
        "FFF6DF" => [ "name" => "Varden"],
        "FFF6F5" => [ "name" => "Rose White"],
        "FFF8D1" => [ "name" => "Baja White"],
        "FFF9E2" => [ "name" => "Gin Fizz"],
        "FFF9E6" => [ "name" => "Early Dawn"],
        "FFFACD" => [ "name" => "Lemon Chiffon"],
        "FFFAF4" => [ "name" => "Bridal Heath"],
        "FFFBDC" => [ "name" => "Scotch Mist"],
        "FFFBF9" => [ "name" => "Soapstone"],
        "FFFC99" => [ "name" => "Witch Haze"],
        "FFFCEA" => [ "name" => "Buttery White"],
        "FFFCEE" => [ "name" => "Island Spice"],
        "FFFDD0" => [ "name" => "Cream"],
        "FFFDE6" => [ "name" => "Chilean Heath"],
        "FFFDE8" => [ "name" => "Travertine"],
        "FFFDF3" => [ "name" => "Orchid White"],
        "FFFDF4" => [ "name" => "Quarter Pearl Lusta"],
        "FFFEE1" => [ "name" => "Half and Half"],
        "FFFEEC" => [ "name" => "Apricot White"],
        "FFFEF0" => [ "name" => "Rice Cake"],
        "FFFEF6" => [ "name" => "Black White"],
        "FFFEFD" => [ "name" => "Romance"],
        "FFFF00" => [ "name" => "Yellow"],
        "FFFF66" => [ "name" => "Laser Lemon"],
        "FFFF99" => [ "name" => "Pale Canary"],
        "FFFFB4" => [ "name" => "Portafino"],
        "FFFFF0" => [ "name" => "Ivory"],
        "FFFFFF" => [ "name" => "White"]
    ];

    private function getHex ($num) {
        $hash = hash("md5", $num, true);
        return substr(bin2hex($hash), 0, 6);
    }

    private function testDate ($date) {
        return preg_match('/\d{4}-\d{2}-\d{2}/', $date);
    }

    public function index (Request $request) {
        $response = [];
        $date = $request->input('date') ? $request->input('date') : date('Y-m-d');
        
        if ($this->testDate($date)) {
            $hex = $this->getHex($date);
            $response['date'] = $date;
            $response['hex'] = "#{$hex}";
            
            return response()->json($response, 200);
        }

        $response['error'] = 'Invalid request';

        return response()->json($response, 200);
    }
}
